---

- name: django-admin.py - Inspect graphite db
  command: "{{ graphite_django_admin }} inspectdb"
  environment:
    DJANGO_SETTINGS_MODULE: graphite.settings
    PYTHONPATH: "{{ graphite_install_path }}/webapp/"
  become: yes
  become_user: "{{ graphite_user }}"
  register: result
  changed_when: False
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true

- name: django-admin.py - Check for secret key warning
  assert:
    that:
      - "'SECRET_KEY' not in result.stderr"

- name: django-admin.py - Sync/create database
  command: "{{ graphite_django_admin }} migrate --run-syncdb --noinput"
  environment:
    DJANGO_SETTINGS_MODULE: graphite.settings
    PYTHONPATH: "{{ graphite_install_path }}/webapp/"
  become: yes
  become_user: "{{ graphite_user }}"
  when: result.stdout.find("AccountMygraph") == -1

- name: django-admin.py - Create superuser account
  command: >
    {{ graphite_django_admin }} createsuperuser
    --username={{ graphite_admin_username }}
    --email={{ graphite_admin_email }}
    --noinput
  environment:
    DJANGO_SETTINGS_MODULE: graphite.settings
    PYTHONPATH: "{{ graphite_install_path }}/webapp/"
  become: yes
  become_user: "{{ graphite_user }}"
  register: superuser_created
  args:
    creates: "{{ graphite_install_path }}/webapp/graphite/.superuser_created"

- name: django-admin.py - Prepare to set up superuser password  # noqa no-handler
  template:
    src: createsuperuser.py.j2
    dest: /tmp/createsuperuser.py
    owner: "{{ graphite_user }}"
    group: "{{ graphite_user }}"
    mode: 0700
  when: superuser_created is changed

- name: django-admin.py - Set superuser password  # noqa no-handler
  shell: >
    {{ graphite_django_admin }}
    shell < /tmp/createsuperuser.py
  environment:
    DJANGO_SETTINGS_MODULE: graphite.settings
    PYTHONPATH: "{{ graphite_install_path }}/webapp/"
  become: yes
  become_user: "{{ graphite_user }}"
  when: superuser_created is changed

- name: django-admin.py - Create lock file  # noqa no-handler
  file:
    path: "{{ graphite_install_path }}/webapp/graphite/.superuser_created"
    state: touch
    owner: root
    group: root
    mode: 0644
  when: superuser_created is changed
