---

- name: restart carbon-cache
  service: name=carbon-cache state=restarted
  when: graphite_enable_carbon_cache

- name: restart carbon-relay
  service: name=carbon-relay state=restarted
  when: graphite_enable_carbon_relay

- name: restart uwsgi
  service: name=uwsgi state=restarted
  when: graphite_enable_uwsgi

- name: reload systemd for carbon
  systemd:
    daemon_reload: yes
  notify:
    - restart carbon-cache
    - restart carbon-relay
