---
- hosts: all
  become: yes
  tasks:
    - name: Bootstrap python for Ansible
      raw: |
        command -v python3 python || (
        command -v apk >/dev/null && sudo apk add --no-progress --update python3 ||
        (test -e /usr/bin/dnf && sudo dnf install -y python3) ||
        (test -e /usr/bin/apt && (sudo apt-get -y update && sudo apt-get install -y python3 python3-apt)) ||
        (test -e /usr/bin/yum && sudo yum -y -qq install python3) ||
        (test -e /usr/sbin/pkg && sudo env ASSUME_ALWAYS_YES=yes pkg update && sudo env ASSUME_ALWAYS_YES=yes pkg install python3) ||
        (test -e /usr/sbin/pkg_add && sudo /usr/sbin/pkg_add -U -I -x python%3.7) ||
        echo "ERROR: Python not bootstrapped due to unknown platform." && exit 234
        )
      become: true
      changed_when: false
      retries: 3
      delay: 10
      register: python_bootstrap
      until: python_bootstrap.rc != 234
      ignore_errors: true

    - name: RedHat | Install a few packages for the tests
      yum:
        name:
          - file
          - nc
      when: ansible_os_family == "RedHat"

    - name: Debian | Install a few packages for the tests
      apt:
        name:
          - curl
          - file
          - netcat
        update_cache: yes
      when: ansible_os_family == "Debian"
